version: '3.1'
services:
  client:
    image: node:onbuild
    command: yarn start
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app

  backend:
    image: node:onbuild
    command: yarn run nodemon server.js --exec babel-node
    ports:
     - "4000:4000"
    volumes:
     - .:/usr/src/app
